name: run main.py

on:
  workflow_dispatch:
      inputs:
        icarros_filter:
          description: "Icarros filter:"
        webmotors_filter:
          description: "Webmotors filter:"
  schedule:
    - cron:  "30 10-23/2,1 * * *" #run after 2h30m every day from 10 - 23 and 1 
    # 10h30, ..., 23h30, 1h30, 10h30, ...

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5

      - name: Setup Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      - name: Execute main.py
        env:
          EMAIL: ${{ secrets.EMAIL }}
          EMAIL_ID: ${{ secrets.EMAIL_ID }}
          PREFERENCES: ${{ secrets.PREFERENCES }}
        run: python main.py

      - name: Show dispatch inputs
        run: echo "Workflow dispatch inputs ${{ github.event.inputs }}"
        
      - name: Commit and push files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add results
          git diff-index --quiet HEAD || (git commit -a -m "[SCRAPING-UPDATE-ACTION] Update results" --allow-empty)
          git push
