name: run main.py

on:
  push:
    branches:
      - "develop"
  pull_request:
    branches:
      - "develop" 
    paths:
      - ".github/workflows/actions.yaml"
  schedule:
    - cron:  "30 */2 * * *" #run after 2h30m every day

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5

      - name: Setup Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: "3.11"

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # run main.py
        run: python src/main.py

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add results
          git diff-index --quiet HEAD || (git commit -a -m "[SCRAPING-UPDATE_ACTION] Update results" --allow-empty)

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: develop
