name: run main.py

on:
  schedule:
    - cron:  "30 10-23/2,1 * * *" #run after 2h30m every day from 10 - 23 and 1 
    # 10h30, ..., 23h30, 1h30, 10h30, ...

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5

      - name: Setup Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: "3.11"

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # run main.py
        run: python main.py

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add results
          git diff-index --quiet HEAD || (git commit -a -m "[SCRAPING-UPDATE_ACTION] Update results" --allow-empty)

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
